# Generated by Django 2.2.3 on 2019-07-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0004_auto_20170622_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cBirthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
